### ISSUE TITLE
Sausage Fattener: Unhandled audio master request: audioMasterGetSampleRate

### ISSUE THREAD

**Issue by polarity** [phantom-code/airwave#33] opened 2015-12-20 20:06 UTC
loads but, changing knobs leads to crash.

```
1450641095.205048043 Sausage Fattener.dll : Initializing host endpoint 1.2.1
1450641095.419827810 Sausage Fattener.dll : Waiting for plugin endpoint request...
1450641095.421818059 Sausage Fattener.dll : Request from plugin endpoint received, sending response
1450641095.421845589 Sausage Fattener.dll : Initializing VST plugin...
1450641096.040178136 Sausage Fattener.dll : Unhandled audio master request: audioMasterGetSampleRate
1450641096.040232069 Sausage Fattener.dll : VST plugin is initialized
1450641096.040239909 Sausage Fattener.dll : Host endpoint is initialized
1450641096.040248991  Sausage Fattener.so : Plugin endpoint is initialized
1450641096.040643608 Sausage Fattener.dll : Audio thread started
```
thx for your work dude, airwave is ace. <3

**Comment by phantom-code** [comment] 2015-12-20 20:33
It's strange because Sausage Fattener worked earlier. Will see what I can do.

**Comment by polarity** [comment] 2015-12-20 20:35
used one of the airwave binaries 1.2.1. maybe too old?

**Comment by phantom-code** [comment] 2015-12-20 20:49
No, the 1.2.1 is the latest version and Sausage Fattener works with it. Perhaps something changed in wine itself, but I need to review the issue anyway.

**Comment by phantom-code** [comment] 2016-01-08 11:58
The issue is fixed in the develop branch. Sorry for such big delay and thanks for reporting!

**Closed by phantom-code** 2016-01-08 11:58 UTC

**Comment by polarity** [comment] 2016-01-08 13:17
thx for fixing this and your work in general. much appreciated!
